ci: 버전 관리 추가

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,16 +1,35 @@
 name: Github-actions 자동 배포
 
+
 on:
   push:
-    branches:
-      - main
-
+    tags:
+      - 'v*'
 jobs:
   Deploy:
     runs-on: ubuntu-latest
 
-
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Validate Git tag and build.gradle version match
+        run: |
+          # 태그에서 버전 추출
+          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
+          
+          # build.gradle에서 version 추출
+          FILE_VERSION=$(grep "^version" build.gradle | sed -E "s/version *= *'([^']+)'/\1/")
+          
+          echo "Git tag version: $TAG_VERSION"
+          echo "build.gradle version: $FILE_VERSION"
+          
+          # 태그와 build.gradle의 실행 파일 버전이 같은지 확인
+          if [ "$TAG_VERSION" != "$FILE_VERSION" ]; then
+            echo "error: Tag version ($TAG_VERSION) does not match build.gradle version ($FILE_VERSION)."
+            exit 1
+          fi
+
       - name: SSH로 LightSail 인스턴스 접속해서 원격에서 최신 코드 pull 받고 빌드 -> 빌드 파일 실행 하기
         uses: appleboy/ssh-action@v1
         env:
@@ -25,10 +44,10 @@ jobs:
             set -x
             
             cd /home/ubuntu/BackEnd-integration
-            git checkout refactor/github-actions
+            git checkout main
 
             # 최신 코드 가져오기
-            git pull origin refactor/github-actions
+            git pull origin main
 
             # .env 파일 복원
             echo "$ENV_FILE" | base64 -d > .env
